//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/test.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/test.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Test: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Test()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""test"",
    ""maps"": [
        {
            ""name"": ""test_anim"",
            ""id"": ""9e05d07f-b7e1-45ab-96e1-e5eb99478921"",
            ""actions"": [
                {
                    ""name"": ""change_pose"",
                    ""type"": ""Button"",
                    ""id"": ""48e97ea2-8da1-42e6-ad3b-45301c619ab8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""change_mesh"",
                    ""type"": ""Button"",
                    ""id"": ""c12f41b7-3afe-4a2f-aaf3-7d68e59fd1d0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1e014e5d-cabf-4ac8-8ce0-5cd3ce16d47b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""change_pose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87a75817-68c0-49ac-9891-85a356841822"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""change_mesh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // test_anim
        m_test_anim = asset.FindActionMap("test_anim", throwIfNotFound: true);
        m_test_anim_change_pose = m_test_anim.FindAction("change_pose", throwIfNotFound: true);
        m_test_anim_change_mesh = m_test_anim.FindAction("change_mesh", throwIfNotFound: true);
    }

    ~@Test()
    {
        UnityEngine.Debug.Assert(!m_test_anim.enabled, "This will cause a leak and performance issues, Test.test_anim.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // test_anim
    private readonly InputActionMap m_test_anim;
    private List<ITest_animActions> m_Test_animActionsCallbackInterfaces = new List<ITest_animActions>();
    private readonly InputAction m_test_anim_change_pose;
    private readonly InputAction m_test_anim_change_mesh;
    /// <summary>
    /// Provides access to input actions defined in input action map "test_anim".
    /// </summary>
    public struct Test_animActions
    {
        private @Test m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Test_animActions(@Test wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "test_anim/change_pose".
        /// </summary>
        public InputAction @change_pose => m_Wrapper.m_test_anim_change_pose;
        /// <summary>
        /// Provides access to the underlying input action "test_anim/change_mesh".
        /// </summary>
        public InputAction @change_mesh => m_Wrapper.m_test_anim_change_mesh;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_test_anim; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Test_animActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Test_animActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Test_animActions" />
        public void AddCallbacks(ITest_animActions instance)
        {
            if (instance == null || m_Wrapper.m_Test_animActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Test_animActionsCallbackInterfaces.Add(instance);
            @change_pose.started += instance.OnChange_pose;
            @change_pose.performed += instance.OnChange_pose;
            @change_pose.canceled += instance.OnChange_pose;
            @change_mesh.started += instance.OnChange_mesh;
            @change_mesh.performed += instance.OnChange_mesh;
            @change_mesh.canceled += instance.OnChange_mesh;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Test_animActions" />
        private void UnregisterCallbacks(ITest_animActions instance)
        {
            @change_pose.started -= instance.OnChange_pose;
            @change_pose.performed -= instance.OnChange_pose;
            @change_pose.canceled -= instance.OnChange_pose;
            @change_mesh.started -= instance.OnChange_mesh;
            @change_mesh.performed -= instance.OnChange_mesh;
            @change_mesh.canceled -= instance.OnChange_mesh;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Test_animActions.UnregisterCallbacks(ITest_animActions)" />.
        /// </summary>
        /// <seealso cref="Test_animActions.UnregisterCallbacks(ITest_animActions)" />
        public void RemoveCallbacks(ITest_animActions instance)
        {
            if (m_Wrapper.m_Test_animActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Test_animActions.AddCallbacks(ITest_animActions)" />
        /// <seealso cref="Test_animActions.RemoveCallbacks(ITest_animActions)" />
        /// <seealso cref="Test_animActions.UnregisterCallbacks(ITest_animActions)" />
        public void SetCallbacks(ITest_animActions instance)
        {
            foreach (var item in m_Wrapper.m_Test_animActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Test_animActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Test_animActions" /> instance referencing this action map.
    /// </summary>
    public Test_animActions @test_anim => new Test_animActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "test_anim" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Test_animActions.AddCallbacks(ITest_animActions)" />
    /// <seealso cref="Test_animActions.RemoveCallbacks(ITest_animActions)" />
    public interface ITest_animActions
    {
        /// <summary>
        /// Method invoked when associated input action "change_pose" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChange_pose(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "change_mesh" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChange_mesh(InputAction.CallbackContext context);
    }
}
